[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

[features]
# Process and display mathematical expressions in the UI (default: true).
latex = true

# Authorize users to upload files with messages (default: true).
multi_modal = true

[files]
# Allow users to upload files alongside messages
upload_file = true
# Maximum file size in MB
max_size_mb = 100
# Accepted file types
accept = ["application/zip", "application/x-zip-compressed", ".zip"]

[UI]
# Name of the app and chatbot.
name = "Universal Tester"

# Show the readme while the thread is empty.
show_readme_as_default = false

# Description of the app and chatbot. This is used for HTML tags.
description = "AI-powered agent that generates comprehensive test cases for software projects"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file should be placed in the .chainlit/static directory.
# custom_css = "/static/custom.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file should be placed in the .chainlit/static directory.
# custom_js = "/static/custom.js"

# Override default MUI light theme. (Check theme.py)
[UI.theme]
#layout = "wide"
#font_family = "Inter, sans-serif"

[UI.theme.light]
#background = "#FAFAFA"
#paper = "#FFFFFF"

#[UI.theme.dark]
#background = "#1E1E1E"
#paper = "#262626"

# Color system for the user interface.
#primary = "#F80061"
#background = "#26195c"
#surface = "#213c7a"

[meta]
generated_by = "1.0.505"
